language: java	
jdk: oraclejdk8
install: ant
notifications:
  email:
    on_success: never
    on_failure: never    
before_install:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/classicwuhao/uran/lib
