#!/bin/bash
PATH="build/classes"
JAVA=/usr/bin/java

$JAVA -cp "build/classes/:/home/haowu/z3/build/com.microsoft.z3.jar" test.formula.testFormula
$JAVA -cp "build/classes/:/home/haowu/z3/build/com.microsoft.z3.jar" test.formula.bv.test1
$JAVA -cp "build/classes/:/home/haowu/z3/build/com.microsoft.z3.jar" test.formula.array.test_array

